### ISSUE TITLE
NPE on report parameter validation

### ISSUE THREAD

**Issue by m-orlova** [Haulmont/jmix-reports#104]
1. Open Reports -> Reports
2. Click on the "Create" button
3. Specify name and default template
4. Select the "Parameters and formats" tab
5. Click on the "Create" button to add a parameter
6. Specify caption, alias and parameter type (e.g. String parameter)
7. Select the "Validation" tab
8.  Set "Validate" to true and fill the script to validaton:
![image](https://user-images.githubusercontent.com/71265042/114881770-5bb42800-9e14-11eb-97bd-1cc4d76e0061.png)
9. Save a parameter
10. Click on the "Run" button
11. Input the parameter value and run the report
AR: 
![image](https://user-images.githubusercontent.com/71265042/114880879-86ea4780-9e13-11eb-87c6-dc69f66cf624.png)

**Comment by gorbunkov** [comment]
@Desire456 Check it, probably the issue is already fixed

**Comment by Desire456** [comment]
Can't reproduce it now
