### ISSUE TITLE
Table template columns are shown in the incorrect order

### ISSUE THREAD

**Issue by m-orlova** [Haulmont/jmix-reports#127]
Steps to reproduce:
1. Open the Report browser
2. Click on the "Create" button and select "New"
3. Add a new band with a dataset
4. Add a default template with output type = "Table"
5. In the template editor, add a band (from step 3) and two columns
![image](https://user-images.githubusercontent.com/71265042/117273171-ed8bdf80-ae6c-11eb-9d57-76e89c3433f2.png)
6. Change columns order:
![image](https://user-images.githubusercontent.com/71265042/117273247-0399a000-ae6d-11eb-896c-f45cf03206a0.png)
7. Save a template
8. Edit a template
AR: columns are shown in the incorrect order
![image](https://user-images.githubusercontent.com/71265042/117273567-4f4c4980-ae6d-11eb-80d0-c17a833c4c29.png)

**Comment by Desire456** [comment]
The same problem with bands
