### ISSUE TITLE
Migrate Wizard screen

### ISSUE THREAD

**Issue by NikitaShchienko** [Haulmont/jmix-reports#19]
### Description
Migrate screens for quick report generation.

#### Progress:
- [ ] Migrate basic functionality - **2021-04-19 80%** (Complete items from remarks)
- [x] Convert Generators to Spring Beans
- [x] Create a replacement for a query filter 
- [ ] Refactoring - **2021-04-19 50%**

#### Remarks
- Revert the logic of opening _RegionsEditor_ before the second step
- Fix Popup Button in the second step

**Comment by gorbunkov** [comment]
Separate issues have been created for functionality not implemented here
