### ISSUE TITLE
Incorrect display of the Template name

### ISSUE THREAD

**Issue by glebfox** [Haulmont/jmix-reports#192]
**Minimal reproducible example**
1. Create a new report using the wizard
2. Go through the first two steps

**Expected behavior**
The template name is displayed like this Template for report "Report for entity " ... or added extra space

**Actual behavior**
![Screenshot 2021-06-22 at 12 08 27](https://user-images.githubusercontent.com/6077149/122888083-92497a00-d352-11eb-8c8c-88b166ef4b50.png)

---

Port: https://github.com/cuba-platform/reports/issues/282

**Comment by konyashkina** [comment]
Tested on 
Jmix version: 1.1.0-SNAPSHOT
Jmix Studio plugin version: 1.1.SNAPSHOT3294-211
IntelliJ version: IntelliJ IDEA 2021.1.3 (Community Edition).
