### ISSUE TITLE
Port: Import reports to deleted groups

### ISSUE THREAD

**Issue by Desire456** [Haulmont/jmix-reports#194]
See https://github.com/cuba-platform/reports/issues/283 and https://github.com/cuba-platform/reports/issues/285

**Comment by DartVerder** [comment]
https://github.com/cuba-platform/reports/issues/285 - successful ported
https://github.com/cuba-platform/reports/issues/283 - failed

**TC:**
1. Create new project and add report add-on
2. Run application
3. Create new report group
4. Create report and set group = new group
5. Export created report
6. Create new project (or recreate DB in existing) and add report add-on
7. Run application
8. Import report -> click ok

**AR:**
an exception was thrown 
[NoResultException.txt](https://github.com/Haulmont/jmix-reports/files/7129331/NoResultException.txt)
if you click close - file displayed as selected in "import report" window - click ok 
an exception was thrown 
[NPE_reports.txt](https://github.com/Haulmont/jmix-reports/files/7129340/NPE_reports.txt)
