### ISSUE TITLE
Port: Only default template displayed in Run report screen if report run from the report editor screen

### ISSUE THREAD

**Issue by Desire456** [Haulmont/jmix-reports#197]
See https://github.com/cuba-platform/reports/issues/166

**Comment by konyashkina** [comment]
Tested on 
Jmix version: 1.1.0-SNAPSHOT
Jmix Studio plugin version: 1.1.SNAPSHOT3423-211
IntelliJ version: IntelliJ IDEA 2021.1.3 (Community Edition)
OS: Windows 10 Pro
Browser: Google Chrome 92.0.4515.131

Verified
Related bug in opened: https://github.com/Haulmont/jmix-reports/issues/208
