### ISSUE TITLE
Incorrect display of the Template name (port to 1.0.x)

### ISSUE THREAD

**Issue by glebfox** [Haulmont/jmix-reports#198]
See #192

**Comment by konyashkina** [comment]
Tested on: 
Jmix version: 1.0.999-SNAPSHOT
Jmix Studio plugin version: 1.0.SNAPSHOT3289-211
IntelliJ version: IntelliJ IDEA 2021.1.3 (Community Edition)

![jmix-report-template-with-very-long-name-test-in-release-branch](https://user-images.githubusercontent.com/85500330/126633582-30cb7599-426f-48ad-ae71-df6f864475cc.png)

Verified.
