### ISSUE TITLE
UI: Edit report page doesn't fit some screen settings (resolution and scale) (port to 1.0)

### ISSUE THREAD

**Issue by gorbunkov** [Haulmont/jmix-reports#206]
See #199

**Comment by konyashkina** [comment]
Tested on 
Jmix version: 1.0.999-SNAPSHOT
Jmix Studio plugin version: 1.0.1.SNAPSHOT3486-212
IntelliJ version: IntelliJ IDEA 2021.2.1 (Ultimate Edition)
