### ISSUE TITLE
Report templates are shown twice in a list if one is custom

### ISSUE THREAD

**Issue by konyashkina** [Haulmont/jmix-reports#208]
When user try to run a report templates are shown twice in a list if one of them is marked 'Is custom'.

Jmix version: 1.1.0-SNAPSHOT
Jmix Studio plugin version: 1.1.SNAPSHOT3423-211
IntelliJ version: IntelliJ IDEA 2021.1.3 (Community Edition)
OS: Windows 10 Pro
Browser: Google Chrome 92.0.4515.131

**Pre-condition:** Reports add-on is installed
there are following dependencies in build.gradle:

```
implementation 'io.jmix.reports:jmix-reports-starter'
implementation 'io.jmix.reports:jmix-reports-ui-starter'
```

**Steps to reproduce:**

1. Run Jmix application, open it in browser.
2. Go to Reports.
3. Create a new Report. Add more than one template into it.
4. Set 'Is custom' flag for the one of templates.
5. Save the report and close the report editor. (Click Save, then click OK).
6. Run the report from the Report browser. (Click Run).
7. ('Input parameters and run report' dialog window appears successfully).
8. In the dialog window click Template drop-down list.

**ER:** Each template header is shown once in the drop-down list.

**AR:** Template headers are shown twice in the list.

![jmix report template 002 Google Chrome 16082021 small](https://user-images.githubusercontent.com/85500330/129554936-3a1823b4-dc51-4017-9954-50884ed8e116.png)

![jmix report template 004 Google Chrome 16082021 small](https://user-images.githubusercontent.com/85500330/129554947-c95cc9f7-18ce-466d-8d8f-b815921f4d8f.png)

**Comment by Desire456** [comment]
The value of the `custom` property makes no sense in this case. That occurs because we have double templates loading in case of report is not temporary.

**Comment by konyashkina** [comment]
Tested on 
Jmix version: 1.1.0-SNAPSHOT
Jmix Studio plugin version: 1.1.SNAPSHOT3433-211
IntelliJ version: IntelliJ IDEA 2021.1.3 (Community Edition)

Verified.
