### ISSUE TITLE
Migrate PivotTable and Chart screens

### ISSUE THREAD

**Issue by NikitaShchienko** [Haulmont/jmix-reports#21]
- [x] Charts:
	- [x] Chart template in template editor 
	- [x] 'Show charts' screen
- [x] Pivot table:
	- [x] Pivot table template in template editor
	- [x] 'Show pivot tables' screen

**Comment by m-orlova** [comment]
@NikitaShchienko see [Migrate Charts #170](https://github.com/Haulmont/jmix-ui/issues/170)
