### ISSUE TITLE
Excel button is broken on pivot reports

### ISSUE THREAD

**Issue by reznikova21** [Haulmont/jmix-reports#211]
**Environment**:

OS: Mac

Jmix version: 1.1.0-SNAPSHOT

**Preconditions for**  <https://github.com/jmix-projects/sample-sales-jmix>:

1. Switch to branch with_some_addons

**Preconditions for** new jmix project:
1\. Add add-ons Pivot Table and Reports
2\. Create JPA entity PersonPart with attributes: *number*: Integer, *description*: String -\> add standard screens
3\. Create JPA entity Person with attributes: *name*: String, *age*: integer, *parts*: association or composition One-to-many with PersonPart entity -\> add standard screens
\-\> in fetch plan add parts -\> complete creation
4\. Gradle -\>Task -\> application -\> bootRun
5\. Open <http://localhost:8080/> -\> login (admin/admin)
6\. Create one entity PersonPart and Person

**Steps:**

 1. Reports -\> Reports -\> Create -\> Using wizard -\> Entity: Person, Template type: Table -\> Report type -\>  Report for list of entities
 2. Select name and age -\> ok -\> Next - \> Save -\> OK
 3. In Reports select the created report -\> Edit
 4. Templates: Select a row in the table with the DEFAULT code -\>  Edit
 5. Select: Output type: Pivot table, Band: Person, Mode: Sum -\> ok - \> Default aggregation: Sum
 6. Properties options -\>  Create -\>  Row
 7. Name "Test"  -\>  Ok
 8. Create -\> select Aggregation
 9. Age "5" -\> Ok - \> OK
10. Save -\> Run -\> Select Entity -\> Run -\> Excel

**ER**:

The report is exported.

**AR:**
<img width="822" alt="Untitled114 application 2021-09-10 13-04-41" src="https://user-images.githubusercontent.com/87806606/132848548-5c960834-60a0-40b0-b564-b6e298b585b4.png">

**Comment by gorbunkov** [comment]
@reznikova21 You've probably created an invalid pivot table. The pivot table should contain both columns and rows properties. For instance I have a table that displays a count of persons with the given name and with the given age, e.g.

<img width="563" alt="image" src="https://user-images.githubusercontent.com/7888486/134010347-0491eeaf-076e-48a7-b952-0fd098dc9f5e.png">

This table says that there are 2 Bobs of the age 5 and and one Bob of 88. This kind of pivot table (it has both rows and columns) is exported correctly.

<img width="1232" alt="image" src="https://user-images.githubusercontent.com/7888486/134010598-a9df9573-f729-4959-955b-9e7a35bbdda9.png">

**Comment by reznikova21** [comment]
when adding a column, the bug is not reproduced
