### ISSUE TITLE
Liquibase validation exception

### ISSUE THREAD

**Issue by aiden-izumi** [Haulmont/jmix-reports#219]
When I migrate my Jmix project from version 1.0.1 to version 1.1.0 I'm getting a liquibase.exception.ValidationFailedException related to 001-reports.xml.
The problem is with checksums.
I will attach stacktrace to the issue

_

How to reproduce: 
- Create a Jmix project (via Intellij Idea Jmix plugin) of 1.0.1 version
- Add reports addon (via the Jmix plugin)
- Create database
- Migrate version from 1.0.1 to 1.1.0 (via the Jmix plugin)
- Try to launch application, accepting changes in liquibase

_
The file: [stacktrace.txt](https://github.com/Haulmont/jmix-reports/files/7452906/stacktrace.txt)

**Comment by aiden-izumi** [comment]
Probably it is just incorrect checksum
`<validCheckSum>8:f5da7222d918810deb69ba452ee5560e</validCheckSum>`
specified at line 24 of this file:

https://github.com/Haulmont/jmix-reports/blob/master/reports/src/main/resources/io/jmix/reports/liquibase/changelog/001-reports.xml

**Comment by gorbunkov** [comment]
@lovtsovaik I can't reproduce the problem. Could you please check?

**Comment by reznikova21** [comment]
1.2.0-SNAPSHOT - verified

**Comment by reznikova21** [comment]
I can't reproduce the problem

**Comment by gorbunkov** [comment]
@aiden-izumi we could not reproduce the issue using the steps described above. Maybe you missed some step in the description? Do you still get the errors?

**Comment by aiden-izumi** [comment]
@gorbunkov 
The problem is still there. I have create a sample-repository: https://github.com/aiden-izumi/reports-script-problem
And this is my Intellij Idea terminal output: [log.txt](https://github.com/Haulmont/jmix-reports/files/7569395/log.txt)

**Comment by ket4z** [comment]
Confirming the problem exists. Not noticing this one I have filed a duplicate one here https://github.com/Haulmont/jmix-reports/issues/223 yesterday, sorry :/

**Comment by gorbunkov** [comment]
The problem was reproduced on postgresql. Additional validCheckSum has been added to the problematic changeSet.

For QA: please check migration for different DBMS

**Comment by reznikova21** [comment]
Also the problem was reproduced on
1. Oracle
2. MS SQL

 Not reproduced on
1. MySQL
2. MariaDB

**Comment by reznikova21** [comment]
1.2.0-SNAPSHOT - verified
