### ISSUE TITLE
Group attribute isn't visible after adding Multitenancy add-on

### ISSUE THREAD

**Issue by reznikova21** [Haulmont/jmix-reports#225]
**Description**
See [forum topic](https://forum.jmix.ru/t/atribut-gruppa-ne-otobrazhaetsya-v-ui/254).

**Steps to reproduce**

1. Create new jmix project
2. Add Reports add-on
3. Launch the app > Login > Create report > Save > Ок

![image](https://user-images.githubusercontent.com/87806606/148775387-6d386314-aa38-46fd-86e1-e3acaae6ead1.png)

4. Stop the app
5. Add Multitenancy add-on
6. Launch the app > Login > Reports

**ER**: Group attribute is visible

**AR**: Group attribute is't visible
![image](https://user-images.githubusercontent.com/87806606/148774961-d1ed9f0a-8d62-4a84-b527-626e89774db9.png)

**Comment by dtaimanov** [comment]
Fixed in  Haulmont/jmix-multitenancy#22
