### ISSUE TITLE
FileRef doesn't fit into outputDocument field

### ISSUE THREAD

**Issue by n-13** [Haulmont/jmix-reports#228]
https://github.com/Haulmont/jmix-reports/blob/4e4bb3f2511e197a5519d41f5c10695336fb4f36/reports/src/main/java/io/jmix/reports/entity/ReportExecution.java#L81
Field at database has type varchar(255)
Serialized value of FileRef doesn't fit in 255 characters. 

https://github.com/Haulmont/jmix-core/blob/bd340cd860b6acd28e6e343780da9c44590aa8bc/core/src/main/java/io/jmix/core/FileRef.java#L117
At least url-encoded fileName with non-latin characters can be 3 times larger.

IMHO Lob annotation is missed.

**Comment by knstvk** [comment]
@GlebDurygin - add `preConditions` to `005-migrate-reports.xml`:
```
        <preConditions onFail="MARK_RAN">
            <tableExists tableName="REPORT_REPORT"/>
        </preConditions>
```

**Comment by Afanasevaa36** [comment]
Jmix version: 1.2-SNAPSHOT - verified
