### ISSUE TITLE
ReportWizardCreator lose locale messages

### ISSUE THREAD

**Issue by Rus226** [Haulmont/jmix-reports#229]
io.jmix.reportsui.screen.report.wizard.ReportWizardCreator#onNextBtnClick

156 line, fillEntityMsg - does not exist

**Comment by lovtsovaik** [comment]
@artemy63 please add QA notes

**Comment by artemy63** [comment]
For QA:
1. Start  creating new Report using wizard
2. Do not fill `Entity` field on the first step and click on the `Next` button
ER: Notification is shown with a message about necessity to fill Entity field and it is localized

**Comment by Afanasevaa36** [comment]
Jmix version: 1.2.0-SNAPSHOT - Verified
