### ISSUE TITLE
RunReport action always displays all exising reports

### ISSUE THREAD

**Issue by gorbunkov** [Haulmont/jmix-reports#33]
Reports are not filtered using the information from the Roles and Screens tab. The action always displays a list of all available reports

**Comment by KartonDCP** [comment]
Solved with editing report editor init and restriction logics

**Comment by KartonDCP** [comment]
Create many reports with different cases
![Снимок экрана (16)](https://user-images.githubusercontent.com/43281522/110794968-5a2c9880-8287-11eb-8771-8b130b0d7bdf.png)
![Снимок экрана (18)](https://user-images.githubusercontent.com/43281522/110794973-5b5dc580-8287-11eb-9942-3aa7e1b268fd.png)

**Comment by KartonDCP** [comment]
Current context test:
* FullAccess role 
* NewEntity Screen = current screen
* NewEntity = current param
got expected behavior 
![Снимок экрана (17)](https://user-images.githubusercontent.com/43281522/110794994-6153a680-8287-11eb-817c-db89b1a96b15.png)
