### ISSUE TITLE
IllegalArgumentException: Unable to find action type: excelExport

### ISSUE THREAD

**Issue by m-orlova** [Haulmont/jmix-reports#34]
1. Open Report Browser
2. Select a report
3. Click on the "Execution History" button

**AR:**
![image](https://user-images.githubusercontent.com/71265042/108028560-7b61e680-7045-11eb-87b2-298b7d186cb9.png)

**Comment by KartonDCP** [comment]
Not a bug of Reports. Its bug of Jmix-ui-export module https://github.com/Haulmont/jmix-ui/issues/371

**Comment by KartonDCP** [comment]
> Not a bug of Reports. Its bug of Jmix-ui-export module [Haulmont/jmix-ui#371](https://github.com/Haulmont/jmix-ui/issues/371)

**Outdated, was sovled in UI **
