### ISSUE TITLE
Unlocalized message from listPrintForm action

### ISSUE THREAD

**Issue by alexbudarov** [Haulmont/jmix-reports#52]
- new project
- add reporting addon
- add listPrintForm action to user browser table
- run application, invoke action

![image](https://user-images.githubusercontent.com/6158807/110213487-b4a9ab80-7eb9-11eb-8d25-802fa2f8a7d7.png)

**Comment by KartonDCP** [comment]
Hello! This issue is a duplicate of [https://github.com/Haulmont/jmix-reports/issues/36]
