### ISSUE TITLE
Can't make listPrintForm display reports

### ISSUE THREAD

**Issue by alexbudarov** [Haulmont/jmix-reports#56]
I created report with input parameter, screens and roles.

But listPrintForm action in target screen (user browser) still says "no reports found".

SQL console shows that input_entity_types_idx and roles_idx columns are empty, not filled as they should.

[ikna.zip](https://github.com/Haulmont/jmix-reports/files/6095722/ikna.zip)
[User Info copy.zip](https://github.com/Haulmont/jmix-reports/files/6095728/User.Info.copy.zip)

![image](https://user-images.githubusercontent.com/6158807/110214570-9eeab500-7ebe-11eb-82d3-119c5ab0b801.png)
![image](https://user-images.githubusercontent.com/6158807/110214581-ac07a400-7ebe-11eb-8dfb-2eb5c3116287.png)
![image](https://user-images.githubusercontent.com/6158807/110214589-b4f87580-7ebe-11eb-84ac-13c00bd65487.png)

**Comment by KartonDCP** [comment]
Hello! This issue is part of #33 
Its already solved for 'fieldx' Idx initialization values.
