### ISSUE TITLE
Can't save report after remove a role

### ISSUE THREAD

**Issue by BryanYin** [Haulmont/jmix-reports#69]
Steps:
1. create a report, in “Roles and Screens” tab, add a role, e.g. Full Access role.
2. save the report.
3. open the report for editing.
4. remove the role and save again.

ER: report saved.
AR: Error occurred:
![image](https://user-images.githubusercontent.com/25950822/112285849-b4851a80-8cc5-11eb-992f-9d90c1c2d872.png)

logs here:
`2021-03-24 17:21:02.723  WARN 21484 --- [nio-8080-exec-1] eclipselink.logging.all                  : Exception [EclipseLink-4002] (Eclipse Persistence Services - 2.7.7.2-jmix): org.eclipse.persistence.exceptions.DatabaseException
Internal Exception: java.sql.SQLIntegrityConstraintViolationException: integrity constraint violation: unique constraint or index violation; PK_REPORT_REPORT table: REPORT_REPORT
Error Code: -104
Call: INSERT INTO REPORT_REPORT (ID, CODE, CREATE_TS, CREATED_BY, DELETE_TS, DELETED_BY, DESCRIPTION, INPUT_ENTITY_TYPES_IDX, LOCALE_NAMES, NAME, REPORT_TYPE, REST_ACCESS, ROLES_IDX, SCREENS_IDX, SYS_TENANT_ID, IS_SYSTEM, UPDATE_TS, UPDATED_BY, VERSION, XML, GROUP_ID, DEFAULT_TEMPLATE_ID) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
	bind => [02d4fde0-c0a5-b991-4664-2a98cb415898, null, 2021-03-24 17:21:02.72, admin, null, null, null, null, null, Authors(csv), 10, null, null, null, null, false, 2021-03-24 17:21:02.72, admin, 1, {"metaClass":"report_Report","id":"02d4fde0-c0a5-b991-4664-2a98cb415898","defaultTemplate":{"metaClass":"report_ReportTemplate","id":"30b9588a-6bfd-c192-5238-bc395755aa5f","code":"DEFAULT","customDefinedBy":"200","custom":"false","version":"1","reportOutputType":"80","groovy":"false","createdBy":"admin","customDefinition":"","report":{"metaClass":"report_Report","id":"02d4fde0-c0a5-b991-4664-2a98cb415898"},"name":"Authors.csv","createTs":"2021-03-24T15:59:04.06","updateTs":"2021-03-24T15:59:04.06","alterable":"false"},"bands":[{"metaClass":"report_BandDefinition","id":"f93db4cc-ac8b-a5f3-8ed8-e963e5634c40","orientation":"","childrenBandDefinitions":[{"metaClass":"report_BandDefinition","id":"f5659979-dc39-1ff2-f683-4fc4ca93bc53","orientation":"0","childrenBandDefinitions":[],"name":"data","parentBandDefinition":{"metaClass":"report_BandDefinition","id":"f93db4cc-ac8b-a5f3-8ed8-e963e5634c40"},"report":{"metaClass":"report_Report","id":"02d4fde0-c0a5-b991-4664-2a98cb415898"},"dataSets":[{"metaClass":"report_DataSet","id":"04f40688-cbf0-17e7-caea-7046cba3f377","type":"20","jsonSourceType":"10","name":"data","useExistingView":"false","bandDefinition":{"metaClass":"report_BandDefinition","id":"f5659979-dc39-1ff2-f683-4fc4ca93bc53"},"text":"select e.firstName as first_name,e.lastName as last_name from jmxrpr_Author e;","fetchPlan":"null"}],"position":"0"}],"name":"Root","report":{"metaClass":"report_Report","id":"02d4fde0-c0a5-b991-4664-2a98cb415898"},"dataSets":[],"position":"0"},{"metaClass":"report_BandDefinition","id":"f5659979-dc39-1ff2-f683-4fc4ca93bc53"}],"inputParameters":[],"validationOn":"false","reportType":"10","reportScreens":[{"metaClass":"report_ReportScreen","id":"926b05b7-221d-ab3d-9526-ca0b93ba5a0e","screenId":"jmxrpr_Author.browse","report":{"metaClass":"report_Report","id":"02d4fde0-c0a5-b991-4664-2a98cb415898"}}],"createTs":"2021-03-24T15:59:04.059","group":{"metaClass":"report_ReportGroup","id":"4e083530-0b9c-11e1-9b41-6bdaa41bff94","localeNames":"\u0027en\u003dGeneral\\nru\u003dОбщие\u0027","code":"ReportGroup.default","title":"General","version":"0","createdBy":"admin","createTs":"2021-03-16T15:17:51.735"},"updatedBy":"admin","valuesFormats":[],"templates":[{"metaClass":"report_ReportTemplate","id":"30b9588a-6bfd-c192-5238-bc395755aa5f"}],"version":"5","system":"false","createdBy":"admin","name":"Authors(csv)","updateTs":"2021-03-24T16:12:06.765","reportRoles":[]}, 4e083530-0b9c-11e1-9b41-6bdaa41bff94, 30b9588a-6bfd-c192-5238-bc395755aa5f]
Query: InsertObjectQuery(io.jmix.reports.entity.Report-02d4fde0-c0a5-b991-4664-2a98cb415898 [new,managed])`

**Comment by KartonDCP** [comment]
This bug is part of https://github.com/Haulmont/jmix-reports/pull/63 problem and it will be fixed after merged PR.
