### ISSUE TITLE
Adding EditorPrintFormAction cause NPE 

### ISSUE THREAD

**Issue by BryanYin** [Haulmont/jmix-reports#71]
Steps:
1. Create an entity, e.g. Book and it's browser and editor.
2. add button to the Editor, e.g. books editor:
```xml
<hbox id="editActions" spacing="true">
            <button id="commitAndCloseBtn" action="windowCommitAndClose"/>
            <button id="closeBtn" action="windowClose"/>
            <button id="reportButton" icon="PRINT"/>
</hbox>
```
2. in controller, add below code:
```java
    @Inject
    private Button reportButton;

    @Subscribe
    public void onInit(InitEvent event) {
        reportButton.setAction(new EditorPrintFormAction(this,null));
    }
```
3. start the app, in books browser, click "create" button.

ER: book editor opened.
AR:
![image](https://user-images.githubusercontent.com/25950822/112454987-3e031e00-8d94-11eb-97bb-2f9c1b887240.png)

debugging the source code, found that injected **Messages** is null:
![image](https://user-images.githubusercontent.com/25950822/112454798-05634480-8d94-11eb-9f99-62c971cda8a9.png)

**Comment by KartonDCP** [comment]
This occures when you creating any `Action` with `new`. To avoid it you must use `io.jmix.ui.Actions` bean to create any `Action`
It was eplained [here ](https://github.com/Haulmont/jmix-ui/issues/371#issuecomment-795125709)

**Comment by BryanYin** [comment]
OK, tried with `Actions#create()`:
```java
EditorPrintFormAction action = actions.create(EditorPrintFormAction.class.class, "editPrint");
reportButton.setAction(action);
```
New exception is:
```
java.lang.NoSuchMethodException: io.jmix.reportsui.action.list.EditorPrintFormAction.<init>(java.lang.String)
	at java.lang.Class.getConstructor0(Class.java:3082)
	at java.lang.Class.getConstructor(Class.java:1825)
	at io.jmix.ui.sys.ActionsImpl.createAction(ActionsImpl.java:113)
	at io.jmix.ui.sys.ActionsImpl.create(ActionsImpl.java:90)
	at com.company.jmixreports.screen.book.BookEdit.onInit(BookEdit.java:25)
```

Actually, to creating the action with `new` was copied from CUBA doc, the difference between `EditorPrintFormAction` and other actions is `EditorPrintFormAction` need an additional parameter `EditorScreen` to indicate from which screen the action will be invoked. But `io.jmix.ui.Actions` does not support such creation.

**Comment by gorbunkov** [comment]
I think, for now we can try to go the following way:
* Remove the editor and reportOutputName parameters from action constructor - after that the action may be created using the Actions interface successfully
* Create public setters in action for passing the editor and the reportOutputName

**Comment by Desire456** [comment]
To use EditorPrintFormAction you should create the action using Actions and then set the editor screen. For example:
```
EditorPrintFormAction action = actions.create(EditorPrintFormAction.class);
action.setEditor(this);
action.setReportOutputName(null);
reportButton.setAction(action);
```
