### ISSUE TITLE
Prefix for accessing embedded pictures in HTML templates

### ISSUE THREAD

**Issue by gorbunkov** [Haulmont/jmix-reports#76]
From [CUBA documentation](https://doc.cuba-platform.com/reporting-7.2/reporting.html#template_html):

> You can use the core:// and web:// prefixes to reference to image resources from the web or core module without having to hard-code webPort and webContextName in the template. For example, the image hosted in the deploy\tomcat\webapps\app\VAADIN\images folder can be inserted like:

In Jmix we should use another prefix for that (`web://` and `core://` don't make sense any more). 
Current prefix names should remain for backward compatibility?

**Comment by m-orlova** [comment]
New prefix (resource://) that replaces "web://" and "core://" prefixes is introduced. The resource is searched by a path specified after the "resource://" prefix in the "conf" directory and classpath resources. This logic works only for HTML templates that have PDF as an output type.

**Comment by BryanYin** [comment]
Hi @m-orlova , I tested this, it's not working in Groovy html templates, could you please confirm?
<img width="597" alt="image" src="https://user-images.githubusercontent.com/25950822/120891676-5c12b780-c63c-11eb-9f12-d39929572350.png">

**Comment by m-orlova** [comment]
Hi @BryanYin,
The "resource://" prefix is processed in the case of the template body is HTML but the output type is PDF. In your case the output type is HTML so this case is not related to changes made in this issue.

**Comment by BryanYin** [comment]
Hi @m-orlova,
Thanks for the confirmation, I will add this to the doc.
