### ISSUE TITLE
Finalize a list of parameters passed into groovy band script

### ISSUE THREAD

**Issue by gorbunkov** [Haulmont/jmix-reports#77]
In CUBA the following parameters are passed:
```
        scriptParams.put("reportQuery", reportQuery);
        scriptParams.put("parentBand", parentBand);
        scriptParams.put("params", reportParameters);
        scriptParams.put("persistence", AppBeans.get(Persistence.class));
        scriptParams.put("metadata", AppBeans.get(Metadata.class));
        scriptParams.put("dataManager", AppBeans.get(DataManager.class));
        scriptParams.put("security", AppBeans.get(Security.class));
        scriptParams.put("timeSource", AppBeans.get(TimeSource.class));
        scriptParams.put("userSession", userSessionSource.getUserSession());
        scriptParams.put("userSessionSource", userSessionSource);
        scriptParams.put("transactional", new MethodClosure(this, "transactional"));
        scriptParams.put("validationException", new MethodClosure(this, "validationException"));
```

[CUBA Reports documentation](https://doc.cuba-platform.com/reporting-7.2/reporting.html#structure_groovy) describes them.

I think, in Jmix we should end up with the following parameters list:

* reportQuery
* parentBand
* params
* metadata
* dataManager
* timeSource
* currentAuthentication
* applicationContext

I'm not sure whether we should pass `transactional` and `validationException`. I suggest not to add them for now.

**Comment by m-orlova** [comment]
@gorbunkov 
The final list of parameters passed to the groovy script:

**Groovy/JSON dataset:**
1. reportQuery
2. parentBand
3. params
4. currentAuthentication
5. metadata
6. dataManager
7. timeSource
8. applicationContext
9. validationException (throws ValidationException. This exception is handled and the error notification with a specified message is shown to the user)

**Report parameter validation (the Validation tab in the Parameter editor):**
1. value
2. applicationContext
3. currentAuthentication
4. dataManager
5. metadata
6. invalid

**Report parameter transformation (the Transformation tab in the Parameter editor):**
1. params
2. paramValue
3. dataManager
4. metadata
5. applicationContext

**Cross-parameter validation:**
1. params
2. applicationContext
3. currentAuthentication
4. dataManager
5. metadata
6. invalid

**Custom template script** (if the "Is custom" flag is set as true and "Script" is selected in the "Defined by" field in the Template editor):
1. params
2. rootBand
3. applicationContext
