### ISSUE TITLE
Default template name is unreadable in report editor

### ISSUE THREAD

**Issue by gorbunkov** [Haulmont/jmix-reports#79]
The component looks as follows:

![image.png](https://images.zenhubusercontent.com/5ae421074b5806bc2bd0fd62/4bf9f001-6f40-4611-a7aa-e34aa93e296c)

The text area is too small and the default template name is unreadable. 
One of solutions is to place all the buttons (create template, upload file, etc.) under the single popup button. The popup button will display a list of actions.
Another solution may be to redesign the editor screen so the default template field width is increased.

**Comment by m-orlova** [comment]
@gorbunkov Fixed in #106 . Now it looks as follows:
![image](https://user-images.githubusercontent.com/71265042/116550766-350fea00-a908-11eb-9e1d-c1fa424ea7b7.png)
