### ISSUE TITLE
Spring beans created with new will raise NPEs

### ISSUE THREAD

**Issue by KartonDCP** [Haulmont/jmix-reports#81]
Check this [switch](https://github.com/Haulmont/jmix-reports/blob/8c2ddae94654b91e648cc724923244e0bec797c3/reports-ui/src/main/java/io/jmix/reportsui/wizard/template/TemplateGeneratorImpl.java#L52) 
* `CsvGenerator` created with `new` 
* in `CsvGenerator` we have [reportTemplatePlaceholder]( https://github.com/Haulmont/jmix-reports/blob/8c2ddae94654b91e648cc724923244e0bec797c3/reports-ui/src/main/java/io/jmix/reportsui/wizard/template/generators/CsvGenerator.java#L31) field, that created also with `new`
* [ReportTemplatePlaceholder](https://github.com/Haulmont/jmix-reports/blob/8c2ddae94654b91e648cc724923244e0bec797c3/reports-ui/src/main/java/io/jmix/reportsui/wizard/template/ReportTemplatePlaceholder.java#L34) is Spring Component and it contains `Autowired` fields, for example [messages](https://github.com/Haulmont/jmix-reports/blob/8c2ddae94654b91e648cc724923244e0bec797c3/reports-ui/src/main/java/io/jmix/reportsui/wizard/template/ReportTemplatePlaceholder.java#L46) field
* This field is used in code, but it is not provided by Spring

**Comment by gorbunkov** [comment]
It should be fixed after #19 is merged. Check and close the issue after that.
