### ISSUE TITLE
Incorrect display of the RegionEditor screen

### ISSUE THREAD

**Issue by NikitaShchienko** [Haulmont/jmix-reports#84]
**Problems**:
1 - Incorrect screen name
2 - Shifted icons
3 - Active buttons when the field is not selected
4 - Incomplete field tree

![image](https://user-images.githubusercontent.com/47520144/113357380-fa408380-9354-11eb-8173-4edbf22eecdd.png)

**Additionally**:
5 - Add the ability to select a field with a double click

**Comment by KartonDCP** [comment]
Also:
6 - Selected fields is not readable
7 - Already added attribute message is not localized

![Снимок экрана (37)](https://user-images.githubusercontent.com/43281522/113413328-14b14600-93c3-11eb-9112-38361a4c7776.png)
Also:
